version: '3.4'

services:

  account-api:
    image: gmck/socialdynamo_account:latest
    build:
      context: .
      dockerfile: Account/Dockerfile
    ports:
      - "8080"
    environment:
      ASPNETCORE_HTTP_PORT: 8080
    volumes:
     - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    networks:
      - social-dynamo

  media-api:
    image: gmck/socialdynamo_mediaapi:latest
    build:
      context: .
      dockerfile: Media.API/Dockerfile
    ports:
      - "8080"
    environment:
      ASPNETCORE_HTTP_PORT: 8080
    volumes:
     - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    networks:
      - social-dynamo

  posts-api:
    image: gmck/socialdynamo_postsapi:latest
    build:
      context: .
      dockerfile: Posts.API/Dockerfile
    ports:
      - "8080"
    environment:
      ASPNETCORE_HTTP_PORT: 8080
    volumes:
     - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    networks:
      - social-dynamo

  aggregator-api:
    image: gmck/socialdynamo_baseaggregator:latest
    build:
      context: .
      dockerfile: SocialDynamoAPI/Dockerfile
    ports:
      - "8080"
    environment:
      ASPNETCORE_HTTP_PORT: 8080
    volumes:
     - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    networks:
      - social-dynamo

  gateway-api:
    image: gmck/socialdynamo_apigateway:latest
    build:
      context: .
      dockerfile: SocialDynamoAPI.Gateway/Dockerfile
    ports:
      - "8080"
    environment:
      ASPNETCORE_HTTP_PORT: 8080
    links:
      - account-api
      - media-api
      - posts-api
      - aggregator-api
    depends_on:
      - account-api
      - media-api
      - posts-api
      - aggregator-api
    networks:
      - social-dynamo

networks:
  social-dynamo:
