version: '3.4'

services:

  account-api:
    image: gmck/socialdynamo_account:latest
    build:
      context: .
      dockerfile: Account/Dockerfile
    ports:
      - "5000:443"
      - "8080:80"
    environment:
      ASPNETCORE_HTTPS_PORT: "5000"
      "PUBLIC_PORT": "8080"
    #volumes:
    #  - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    networks:
      - social-dynamo

  media-api:
    image: gmck/socialdynamo_mediaapi:latest
    build:
      context: .
      dockerfile: Media.API/Dockerfile
    ports:
    - "5001:443"
    - "8081:80"
    environment:
      ASPNETCORE_HTTPS_PORT: "5001"
      "PUBLIC_PORT": "8081"
    #volumes:
    #  - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    networks:
      - social-dynamo

  posts-api:
    image: gmck/socialdynamo_postsapi:latest
    build:
      context: .
      dockerfile: Posts.API/Dockerfile
    ports:
      - "5002:443"
      - "8082:80"
    environment:
      ASPNETCORE_HTTPS_PORT: "5002"
      "PUBLIC_PORT": "8082"
    #volumes:
    #  - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    networks:
      - social-dynamo

  aggregator-api:
    image: gmck/socialdynamo_baseaggregator:latest
    build:
      context: .
      dockerfile: SocialDynamoAPI/Dockerfile
    ports:
      - "5003:443"
      - "8083:80"
    environment:
      ASPNETCORE_HTTPS_PORT: "5003"
      "PUBLIC_PORT": "8083"
    #volumes:
    #  - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    networks:
      - social-dynamo

  gateway-api:
    image: gmck/socialdynamo_apigateway:latest
    build:
      context: .
      dockerfile: SocialDynamoAPI.Gateway/Dockerfile
    ports:
      - "9902:80"
      - "9903:443"
    environment:
      ASPNETCORE_HTTPS_PORT: "9903"
    links:
      - account-api
      - media-api
      - posts-api
      - aggregator-api
    depends_on:
      - account-api
      - media-api
      - posts-api
      - aggregator-api
    networks:
      - social-dynamo

networks:
  social-dynamo:
