apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sd-base-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: c3e458f7-b3a6-490b-a32d-9bb56fe6b6fb
    keyvaultName: socialdynamokeys      # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: JwtAudience
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: JwtIssuer
          objectType: secret              
          objectVersion: ""
        - |
          objectName: JwtSecret
          objectType: secret              
          objectVersion: ""
        - |
          objectName: ServiceBus
          objectType: secret
          objectVersion: ""
    tenantId: b3648095-e04e-4313-a735-02088ea30adc                # The tenant ID of the key vault